package gr.insuranceoffice.entity;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.entry;
import static org.assertj.core.api.Assertions.tuple;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.transaction.support.TransactionTemplate;

import gr.insuranceoffice.TestcontainersConfiguration;
import gr.insuranceoffice.security.AppUserDetails;
import gr.insuranceoffice.entity.Vehicle.FuelType;
import gr.insuranceoffice.entity.Vehicle.UsageType;
import gr.insuranceoffice.repository.AppUserRepository;
import gr.insuranceoffice.repository.CustomerRepository;
import gr.insuranceoffice.repository.IntermediaryRepository;
import gr.insuranceoffice.repository.OwnershipRepository;
import gr.insuranceoffice.repository.PolicyRepository;
import gr.insuranceoffice.repository.VehicleRepository;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;

/**
 * Changes go through the repositories, each in its own committed transaction,
 * as they do from the services. The log is read back with SQL.
 */
@SpringBootTest
@Import(TestcontainersConfiguration.class)
class AuditListenerTest {

	@Autowired
	private CustomerRepository customerRepository;

	@Autowired
	private VehicleRepository vehicleRepository;

	@Autowired
	private OwnershipRepository ownershipRepository;

	@Autowired
	private PolicyRepository policyRepository;

	@Autowired
	private IntermediaryRepository intermediaryRepository;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Autowired
	private TransactionTemplate transactionTemplate;

	@Autowired
	private JsonMapper jsonMapper;

	@Autowired
	private AppUserRepository appUserRepository;

	@BeforeEach
	void startEmpty() {
		truncateTables();
	}

	// Other test classes share this database.
	@AfterEach
	void leaveEmpty() {
		truncateTables();
	}

	@Test
	void logsCustomerInsertUpdateAndDelete() {
		Customer customer = customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));
		customer.setMobile("6900000001");
		customer = customerRepository.save(customer);
		customerRepository.delete(customer);

		List<LogRow> log = log();
		assertThat(log).extracting(LogRow::action).containsExactly("CREATE", "UPDATE", "DELETE");
		assertThat(log).extracting(LogRow::entityType).containsOnly("Customer");
		assertThat(log).extracting(LogRow::entityId).containsOnly(customer.getId());

		LogRow created = log.get(0);
		assertThat(created.oldValues()).isNull();
		assertThat(created.newValues()).contains(entry("id", customer.getId().intValue()),
				entry("last_name", "Αλεξίου"), entry("first_name", "Μαρία"), entry("tax_id", "900000080"),
				entry("mobile", null));
		// Generated by the database, not part of the record.
		assertThat(created.newValues()).doesNotContainKey("search_normalized");

		// Only what changed.
		LogRow updated = log.get(1);
		assertThat(updated.oldValues()).containsExactly(entry("mobile", null));
		assertThat(updated.newValues()).containsExactly(entry("mobile", "6900000001"));

		LogRow deleted = log.get(2);
		assertThat(deleted.oldValues()).contains(entry("last_name", "Αλεξίου"), entry("mobile", "6900000001"));
		assertThat(deleted.newValues()).isNull();
	}

	@Test
	void logsVehicleInsertUpdateAndDelete() {
		Vehicle vehicle = vehicleRepository.save(vehicle("WVWZZZ1KZAW123456", "ΑΒΕ-1234"));
		vehicle.setPlate("ΑΒΕ-5678");
		vehicle.setColor("Μαύρο");
		vehicle = vehicleRepository.save(vehicle);
		vehicleRepository.delete(vehicle);

		List<LogRow> log = log();
		assertThat(log).extracting(LogRow::action).containsExactly("CREATE", "UPDATE", "DELETE");
		assertThat(log).extracting(LogRow::entityType).containsOnly("Vehicle");
		assertThat(log.get(0).newValues()).contains(entry("vin", "WVWZZZ1KZAW123456"), entry("plate", "ΑΒΕ1234"),
				entry("plate_normalized", "ABE1234"), entry("first_registration", "2012-05-14"),
				entry("fuel_type", "ΒΕΝΖΙΝΗ"));
		assertThat(log.get(1).oldValues()).contains(entry("plate", "ΑΒΕ1234"), entry("color", "Λευκό"))
				.doesNotContainKeys("vin", "brand");
		assertThat(log.get(1).newValues()).contains(entry("plate", "ΑΒΕ5678"), entry("color", "Μαύρο"));
		assertThat(log.get(2).oldValues()).contains(entry("plate", "ΑΒΕ5678"), entry("plate_normalized", "ABE5678"));
	}

	@Test
	void logsPolicyInsertUpdateAndDelete() {
		Intermediary intermediary = intermediaryRepository.save(intermediary("Παπαδόπουλος Νίκος"));
		Vehicle vehicle = vehicleRepository.save(vehicle("WVWZZZ1KZAW123456", "ΑΒΕ-1234"));
		Policy policy = policyRepository.save(policy(vehicle, "2100000001", LocalDate.of(2026, 3, 1)));
		policy.setIntermediary(intermediary);
		Policy saved = policyRepository.save(policy);

		// Read back as the database holds it: 120.00. Retyping the amount as
		// 120 is not a change; the new end date is.
		Policy reloaded = policyRepository.findById(saved.getId()).orElseThrow();
		reloaded.setPremium(new BigDecimal("120"));
		reloaded.setEndDate(LocalDate.of(2026, 9, 1));
		reloaded = policyRepository.save(reloaded);
		policyRepository.delete(reloaded);

		List<LogRow> log = log().stream().filter(row -> row.entityType().equals("Policy")).toList();
		assertThat(log).extracting(LogRow::action).containsExactly("CREATE", "UPDATE", "UPDATE", "DELETE");
		assertThat(log).extracting(LogRow::entityId).containsOnly(saved.getId());

		assertThat(log.get(0).newValues()).contains(entry("policy_number", "2100000001"),
				entry("vehicle_id", vehicle.getId().intValue()), entry("intermediary_id", null),
				entry("start_date", "2026-03-01"), entry("end_date", "2027-03-01"), entry("surcharge", false));
		assertThat(log.get(1).oldValues()).containsExactly(entry("intermediary_id", null));
		assertThat(log.get(1).newValues()).containsExactly(entry("intermediary_id", intermediary.getId().intValue()));
		assertThat(log.get(2).oldValues()).containsExactly(entry("end_date", "2027-03-01"));
		assertThat(log.get(2).newValues()).containsExactly(entry("end_date", "2026-09-01"));
		assertThat(log.get(3).oldValues()).contains(entry("policy_number", "2100000001"),
				entry("intermediary_id", intermediary.getId().intValue()), entry("end_date", "2026-09-01"));
		assertThat(log.get(3).newValues()).isNull();
	}

	@Test
	void logsIntermediaryInsertUpdateAndDelete() {
		Intermediary intermediary = intermediaryRepository.save(intermediary("Παπαδόπουλος Νίκος"));
		intermediary.setActive(false);
		intermediary = intermediaryRepository.save(intermediary);
		intermediaryRepository.delete(intermediary);

		List<LogRow> log = log();
		assertThat(log).extracting(LogRow::action).containsExactly("CREATE", "UPDATE", "DELETE");
		assertThat(log).extracting(LogRow::entityType).containsOnly("Intermediary");
		assertThat(log).extracting(LogRow::entityId).containsOnly(intermediary.getId());
		assertThat(log.get(0).newValues()).contains(entry("full_name", "Παπαδόπουλος Νίκος"),
				entry("registry_number", "12345"), entry("active", true));
		assertThat(log.get(1).oldValues()).containsExactly(entry("active", true));
		assertThat(log.get(1).newValues()).containsExactly(entry("active", false));
		assertThat(log.get(2).oldValues()).contains(entry("full_name", "Παπαδόπουλος Νίκος"), entry("active", false));
	}

	@Test
	void writesNothingWhenNothingChanged() {
		Customer customer = customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));

		customerRepository.save(customerRepository.findById(customer.getId()).orElseThrow());

		assertThat(log()).extracting(LogRow::action).containsExactly("CREATE");
	}

	@Test
	void recordsAssociationsAsIds() {
		Customer customer = customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));
		Vehicle vehicle = vehicleRepository.save(vehicle("WVWZZZ1KZAW123456", "ΑΒΕ-1234"));
		ownershipRepository.save(ownership(vehicle, customer, "100", true));

		assertThat(log()).filteredOn(row -> row.entityType().equals("Ownership")).singleElement()
				.satisfies(row -> assertThat(row.newValues()).contains(
						entry("vehicle_id", vehicle.getId().intValue()),
						entry("customer_id", customer.getId().intValue()),
						entry("is_primary", true)));
	}

	// The database would cascade to ownership and policy on its own, but
	// nothing would be logged and the rows could not be put back. Loaded
	// first, as the services do before deleting.
	@Test
	void logsThePoliciesAndOwnershipsOfADeletedVehicle() {
		InsuredVehicle insured = insuredVehicle();
		Map<String, List<String>> before = rows("vehicle", "ownership", "policy");

		vehicleRepository.delete(vehicleRepository.findById(insured.vehicle().getId()).orElseThrow());

		assertThat(log()).filteredOn(row -> row.action().equals("DELETE"))
				.extracting(LogRow::entityType, LogRow::entityId)
				.containsExactlyInAnyOrder(
						tuple("Vehicle", insured.vehicle().getId()),
						tuple("Ownership", insured.primaryOwnership().getId()),
						tuple("Ownership", insured.coOwnership().getId()),
						tuple("Policy", insured.expiredPolicy().getId()),
						tuple("Policy", insured.currentPolicy().getId()));
		assertThat(rows("vehicle", "ownership", "policy")).allSatisfy((table, rows) -> assertThat(rows).isEmpty());

		restoreDeleted("Vehicle", "vehicle");
		restoreDeleted("Ownership", "ownership");
		restoreDeleted("Policy", "policy");

		assertThat(rows("vehicle", "ownership", "policy")).isEqualTo(before);
	}

	@Test
	void logsTheOwnershipsOfADeletedCustomer() {
		InsuredVehicle insured = insuredVehicle();
		Customer owner = insured.primaryOwnership().getCustomer();
		Vehicle secondVehicle = vehicleRepository.save(vehicle("WVWZZZ1KZAW654321", "ΚΜΝ-4321"));
		Ownership secondOwnership = ownershipRepository.save(ownership(secondVehicle, owner, "100", true));
		Map<String, List<String>> before = rows("customer", "ownership");

		customerRepository.delete(customerRepository.findById(owner.getId()).orElseThrow());

		assertThat(log()).filteredOn(row -> row.action().equals("DELETE"))
				.extracting(LogRow::entityType, LogRow::entityId)
				.containsExactlyInAnyOrder(
						tuple("Customer", owner.getId()),
						tuple("Ownership", insured.primaryOwnership().getId()),
						tuple("Ownership", secondOwnership.getId()));
		// The co-owner and the vehicles are not the deleted customer's.
		assertThat(ownershipRepository.findAll()).extracting(Ownership::getId)
				.containsExactly(insured.coOwnership().getId());
		assertThat(vehicleRepository.count()).isEqualTo(2);

		restoreDeleted("Customer", "customer");
		restoreDeleted("Ownership", "ownership");

		assertThat(rows("customer", "ownership")).isEqualTo(before);
	}

	// The copy returned by save() still has the empty child lists it was
	// created with. Deleting from it must fail rather than let the database
	// drop the children unlogged.
	@Test
	void refusesToDeleteFromACopyThatDoesNotKnowItsChildren() {
		InsuredVehicle insured = insuredVehicle();
		Map<String, List<String>> before = rows("vehicle", "ownership", "policy");

		assertThatThrownBy(() -> vehicleRepository.delete(insured.vehicle()))
				.isInstanceOf(DataAccessException.class);

		assertThat(rows("vehicle", "ownership", "policy")).isEqualTo(before);
		assertThat(log()).extracting(LogRow::action).containsOnly("CREATE");
	}

	// Task 10: the change is logged against whoever is logged in
	// (ARCHITECTURE §6), by id, as audit_log.user_id is a FK to app_user.
	@Test
	void recordsWhichUserMadeTheChange() {
		AppUser clerk = new AppUser();
		clerk.setUsername("maria");
		clerk.setPasswordHash("{noop}δοκιμή");
		clerk.setFullName("Μαρία Δοκιμαστική");
		clerk.setRole(AppUser.Role.ΥΠΑΛΛΗΛΟΣ);
		appUserRepository.save(clerk);
		AppUserDetails principal = new AppUserDetails(clerk);
		SecurityContextHolder.getContext().setAuthentication(
				new UsernamePasswordAuthenticationToken(principal, null, principal.getAuthorities()));
		try {
			customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));
		} finally {
			SecurityContextHolder.clearContext();
		}

		assertThat(jdbcTemplate.queryForObject("SELECT user_id FROM audit_log WHERE entity_type = 'Customer'",
				Long.class)).isEqualTo(clerk.getId());
	}

	// Nobody is logged in during the Excel import or in a test like this one.
	@Test
	void leavesTheUserEmptyWhenNobodyIsLoggedIn() {
		customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));

		assertThat(jdbcTemplate.queryForObject("SELECT user_id FROM audit_log", Long.class)).isNull();
	}

	@Test
	void rollsBackAnInsertWithTheChange() {
		transactionTemplate.executeWithoutResult(status -> {
			customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));
			assertThat(log()).hasSize(1);
			status.setRollbackOnly();
		});

		assertThat(customerRepository.count()).isZero();
		assertThat(log()).isEmpty();
	}

	@Test
	void rollsBackAnUpdateWithTheChange() {
		Customer customer = customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));

		transactionTemplate.executeWithoutResult(status -> {
			customerRepository.findById(customer.getId()).orElseThrow().setMobile("6900000001");
			customerRepository.flush();
			assertThat(log()).extracting(LogRow::action).containsExactly("CREATE", "UPDATE");
			status.setRollbackOnly();
		});

		assertThat(customerRepository.findById(customer.getId())).get().extracting(Customer::getMobile).isNull();
		assertThat(log()).extracting(LogRow::action).containsExactly("CREATE");
	}

	@Test
	void rollsBackADeleteWithTheChange() {
		InsuredVehicle insured = insuredVehicle();
		Map<String, List<String>> before = rows("vehicle", "ownership", "policy");

		transactionTemplate.executeWithoutResult(status -> {
			vehicleRepository.delete(vehicleRepository.findById(insured.vehicle().getId()).orElseThrow());
			vehicleRepository.flush();
			assertThat(log()).filteredOn(row -> row.action().equals("DELETE")).hasSize(5);
			status.setRollbackOnly();
		});

		assertThat(rows("vehicle", "ownership", "policy")).isEqualTo(before);
		assertThat(log()).extracting(LogRow::action).containsOnly("CREATE");
	}

	// DECISIONS §4: recovery after a hard delete goes through the audit log.
	@Test
	void keepsEnoughToPutBackADeletedCustomer() {
		Customer customer = customer("Αλεξίου", "Μαρία", "900000080");
		customer.setBirthDate(LocalDate.of(1980, 4, 15));
		customer = customerRepository.save(customer);
		customerRepository.delete(customer);

		restoreDeleted("Customer", "customer");

		assertThat(customerRepository.findById(customer.getId())).get()
				.extracting(Customer::getLastName, Customer::getFirstName, Customer::getTaxId, Customer::getBirthDate)
				.containsExactly("Αλεξίου", "Μαρία", "900000080", LocalDate.of(1980, 4, 15));
	}

	private List<LogRow> log() {
		return jdbcTemplate.query("""
				SELECT action, entity_type, entity_id, old_values::text AS old_values, new_values::text AS new_values
				FROM audit_log ORDER BY id
				""", (rs, rowNum) -> new LogRow(rs.getString("action"), rs.getString("entity_type"),
				rs.getLong("entity_id"), parse(rs.getString("old_values")), parse(rs.getString("new_values"))));
	}

	private Map<String, Object> parse(String json) {
		return json == null ? null : jsonMapper.readValue(json, new TypeReference<Map<String, Object>>() {
		});
	}

	// Puts back every row of this type that the log shows as deleted, using
	// only old_values and inserting exactly the columns it recorded.
	private void restoreDeleted(String entityType, String table) {
		List<String> deleted = jdbcTemplate.queryForList(
				"SELECT old_values::text FROM audit_log WHERE action = 'DELETE' AND entity_type = ? ORDER BY id",
				String.class, entityType);
		for (String oldValues : deleted) {
			String columns = String.join(", ", parse(oldValues).keySet());
			jdbcTemplate.update("INSERT INTO %s (%s) SELECT %s FROM jsonb_populate_record(NULL::%s, CAST(? AS jsonb))"
					.formatted(table, columns, columns, table), oldValues);
		}
	}

	// Whole rows as JSON, to compare a table before a delete and after a
	// restore. search_normalized is recomputed by the database either way.
	private Map<String, List<String>> rows(String... tables) {
		Map<String, List<String>> rows = new LinkedHashMap<>();
		for (String table : tables) {
			rows.put(table, jdbcTemplate.queryForList(
					"SELECT (to_jsonb(t) - 'search_normalized')::text FROM %s t ORDER BY id".formatted(table),
					String.class));
		}
		return rows;
	}

	private record LogRow(String action, String entityType, Long entityId, Map<String, Object> oldValues,
			Map<String, Object> newValues) {
	}

	private record InsuredVehicle(Vehicle vehicle, Ownership primaryOwnership, Ownership coOwnership,
			Policy expiredPolicy, Policy currentPolicy) {
	}

	// Two owners and a renewed policy with an intermediary, all committed.
	private InsuredVehicle insuredVehicle() {
		Customer primary = customerRepository.save(customer("Αλεξίου", "Μαρία", "900000080"));
		Customer coOwner = customerRepository.save(customer("Αλεξίου", "Γιώργος", "900000091"));
		Intermediary intermediary = intermediaryRepository.save(intermediary("Παπαδόπουλος Νίκος"));
		Vehicle vehicle = vehicleRepository.save(vehicle("WVWZZZ1KZAW123456", "ΑΒΕ-1234"));
		Ownership primaryOwnership = ownershipRepository.save(ownership(vehicle, primary, "60", true));
		Ownership coOwnership = ownershipRepository.save(ownership(vehicle, coOwner, "40", false));
		Policy expired = policy(vehicle, "2100000001", LocalDate.of(2025, 3, 1));
		expired.setIntermediary(intermediary);
		Policy current = policy(vehicle, "2100000002", LocalDate.of(2026, 3, 1));
		current.setIntermediary(intermediary);
		current.setSurcharge(true);
		current.setSurchargeType(Policy.SurchargeType.ΝΕΟΣ_ΟΔΗΓΟΣ);
		return new InsuredVehicle(vehicle, primaryOwnership, coOwnership, policyRepository.save(expired),
				policyRepository.save(current));
	}

	private static Customer customer(String lastName, String firstName, String taxId) {
		Customer customer = new Customer();
		customer.setLastName(lastName);
		customer.setFirstName(firstName);
		customer.setTaxId(taxId);
		return customer;
	}

	private static Vehicle vehicle(String vin, String plate) {
		Vehicle vehicle = new Vehicle();
		vehicle.setVin(vin);
		vehicle.setPlate(plate);
		vehicle.setBrand("Volkswagen");
		vehicle.setModel("Golf");
		vehicle.setFirstRegistration(LocalDate.of(2012, 5, 14));
		vehicle.setCategory("M1");
		vehicle.setUsageType(UsageType.ΕΙΧ);
		vehicle.setColor("Λευκό");
		vehicle.setEngineCc(1598);
		vehicle.setPowerKw(new BigDecimal("81"));
		vehicle.setFuelType(FuelType.ΒΕΝΖΙΝΗ);
		return vehicle;
	}

	private static Ownership ownership(Vehicle vehicle, Customer customer, String percentage, boolean primary) {
		Ownership ownership = new Ownership();
		ownership.setVehicle(vehicle);
		ownership.setCustomer(customer);
		ownership.setPercentage(new BigDecimal(percentage));
		ownership.setPrimary(primary);
		return ownership;
	}

	// Twelve months here, but no duration is assumed anywhere else.
	private static Policy policy(Vehicle vehicle, String policyNumber, LocalDate startDate) {
		Policy policy = new Policy();
		policy.setVehicle(vehicle);
		policy.setPolicyNumber(policyNumber);
		policy.setInsuranceCompany("Northwind");
		policy.setStartDate(startDate);
		policy.setEndDate(startDate.plusYears(1));
		policy.setPremium(new BigDecimal("120.00"));
		return policy;
	}

	private static Intermediary intermediary(String fullName) {
		Intermediary intermediary = new Intermediary();
		intermediary.setFullName(fullName);
		intermediary.setRegistryNumber("12345");
		return intermediary;
	}

	private void truncateTables() {
		jdbcTemplate.execute("TRUNCATE audit_log, ownership, policy, vehicle, intermediary, customer, app_user "
				+ "RESTART IDENTITY CASCADE");
	}

}
