package gr.insuranceoffice.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;
import org.springframework.test.util.ReflectionTestUtils;

import gr.insuranceoffice.dto.CustomerDto;
import gr.insuranceoffice.dto.IntermediaryDto;
import gr.insuranceoffice.dto.OwnershipDto;
import gr.insuranceoffice.dto.PolicyDto;
import gr.insuranceoffice.dto.VehicleDto;
import gr.insuranceoffice.entity.Customer;
import gr.insuranceoffice.entity.Intermediary;
import gr.insuranceoffice.entity.Ownership;
import gr.insuranceoffice.entity.Policy;
import gr.insuranceoffice.entity.Vehicle;

/**
 * The mapper implementations are generated by the MapStruct annotation
 * processor, so this test only compiles and runs if generation succeeded.
 */
class MapperTest {

	private final CustomerMapper customerMapper = Mappers.getMapper(CustomerMapper.class);

	private final VehicleMapper vehicleMapper = Mappers.getMapper(VehicleMapper.class);

	private final PolicyMapper policyMapper = Mappers.getMapper(PolicyMapper.class);

	private final OwnershipMapper ownershipMapper = Mappers.getMapper(OwnershipMapper.class);

	private final IntermediaryMapper intermediaryMapper = Mappers.getMapper(IntermediaryMapper.class);

	@Test
	void mapsCustomerIncludingItsEnum() {
		Customer customer = new Customer();
		withId(customer, 1L);
		customer.setLastName("Αλεξίου");
		customer.setFirstName("Μαρία");
		customer.setTaxId("123456783");

		CustomerDto dto = customerMapper.toDto(customer);

		assertThat(dto.id()).isEqualTo(1L);
		assertThat(dto.lastName()).isEqualTo("Αλεξίου");
		assertThat(dto.taxId()).isEqualTo("123456783");
		assertThat(dto.entityType()).isEqualTo("INDIVIDUAL");
		// Nullable by design (DECISIONS §1).
		assertThat(dto.mobile()).isNull();
	}

	@Test
	void mapsVehicleKeepingGreekEnumValuesAndNullEngineCc() {
		Vehicle vehicle = new Vehicle();
		withId(vehicle, 2L);
		vehicle.setVin("5YJ3E1EA7JF000001");
		vehicle.setPlate("ΝΖΑ-8812");
		vehicle.setBrand("Tesla");
		vehicle.setModel("Model 3");
		vehicle.setFirstRegistration(LocalDate.of(2021, 5, 4));
		vehicle.setCategory("M1");
		vehicle.setUsageType(Vehicle.UsageType.ΕΙΧ);
		vehicle.setColor("ΜΑΥΡΟ");
		vehicle.setPowerKw(new BigDecimal("211.00"));
		vehicle.setFuelType(Vehicle.FuelType.ΗΛΕΚΤΡΙΣΜΟΣ);

		VehicleDto dto = vehicleMapper.toDto(vehicle);

		assertThat(dto.id()).isEqualTo(2L);
		assertThat(dto.plate()).isEqualTo("ΝΖΑ8812");
		assertThat(dto.fuelType()).isEqualTo("ΗΛΕΚΤΡΙΣΜΟΣ");
		assertThat(dto.usageType()).isEqualTo("ΕΙΧ");
		assertThat(dto.engineCc()).isNull();
		assertThat(dto.powerKw()).isEqualByComparingTo("211.00");
	}

	@Test
	void flattensPolicyAssociationsToIds() {
		Vehicle vehicle = new Vehicle();
		withId(vehicle, 7L);
		Intermediary intermediary = new Intermediary();
		withId(intermediary, 3L);

		Policy policy = new Policy();
		withId(policy, 4L);
		policy.setPolicyNumber("2100000001");
		policy.setVehicle(vehicle);
		policy.setIntermediary(intermediary);
		policy.setInsuranceCompany("ΑΣΦΑΛΙΣΤΙΚΗ Α.Ε.");
		policy.setStartDate(LocalDate.of(2025, 1, 1));
		policy.setEndDate(LocalDate.of(2025, 7, 1));
		policy.setPremium(new BigDecimal("180.00"));
		policy.setSurcharge(true);
		policy.setSurchargeType(Policy.SurchargeType.ΝΕΟΣ_ΟΔΗΓΟΣ);

		PolicyDto dto = policyMapper.toDto(policy);

		assertThat(dto.vehicleId()).isEqualTo(7L);
		assertThat(dto.intermediaryId()).isEqualTo(3L);
		assertThat(dto.surcharge()).isTrue();
		assertThat(dto.surchargeType()).isEqualTo("ΝΕΟΣ_ΟΔΗΓΟΣ");
		assertThat(dto.premium()).isEqualByComparingTo("180.00");
	}

	@Test
	void mapsPolicyWithoutIntermediary() {
		Vehicle vehicle = new Vehicle();
		withId(vehicle, 7L);

		Policy policy = new Policy();
		policy.setPolicyNumber("2100000002");
		policy.setVehicle(vehicle);

		PolicyDto dto = policyMapper.toDto(policy);

		assertThat(dto.vehicleId()).isEqualTo(7L);
		assertThat(dto.intermediaryId()).isNull();
	}

	@Test
	void flattensOwnershipAssociationsToIds() {
		Vehicle vehicle = new Vehicle();
		withId(vehicle, 7L);
		Customer customer = new Customer();
		withId(customer, 8L);

		Ownership ownership = new Ownership();
		ownership.setVehicle(vehicle);
		ownership.setCustomer(customer);
		ownership.setPercentage(new BigDecimal("50.00"));
		ownership.setPrimary(true);

		OwnershipDto dto = ownershipMapper.toDto(ownership);

		assertThat(dto.vehicleId()).isEqualTo(7L);
		assertThat(dto.customerId()).isEqualTo(8L);
		assertThat(dto.percentage()).isEqualByComparingTo("50.00");
		assertThat(dto.primary()).isTrue();
	}

	@Test
	void mapsIntermediary() {
		Intermediary intermediary = new Intermediary();
		withId(intermediary, 3L);
		intermediary.setFullName("Παπαδόπουλος Γιώργος");
		intermediary.setRegistryNumber("123456");

		IntermediaryDto dto = intermediaryMapper.toDto(intermediary);

		assertThat(dto.id()).isEqualTo(3L);
		assertThat(dto.fullName()).isEqualTo("Παπαδόπουλος Γιώργος");
		assertThat(dto.registryNumber()).isEqualTo("123456");
		assertThat(dto.active()).isTrue();
	}

	// Ids are database-generated, so there is no setter to use here.
	private static void withId(Object entity, Long id) {
		ReflectionTestUtils.setField(entity, "id", id);
	}

}
